"""
Pydantic models for artifact generation endpoints
"""

from pydantic import BaseModel
from typing import Any, Dict, Optional


class ArtifactRequest(BaseModel):
    """Request model for artifact generation"""
    topic: str
    num_items: int = 1
    session_context: Optional[Dict[str, Any]] = None  # Session context: session_id, session_title


class ArtifactResponse(BaseModel):
    """Response model for artifact generation
    
    Note: This is a flexible model that accepts any artifact structure
    as generated by the artifact generators (flashcards, MCQ, insights)
    """
    model_config = {"extra": "allow"}  # Allow additional fields
    
    # Common fields that all artifacts have
    artifact_type: str
    version: str
    
    # Additional fields are dynamic based on artifact type
    # Will include: cards/questions/insights, provenance, metrics, etc.
    
    def model_dump(self, **kwargs) -> Dict[str, Any]:
        """Return full artifact as dictionary"""
        return super().model_dump(**kwargs)

